### ISSUE TITLE
Implement privilege related \d commands

### ISSUE THREAD

**Issue by nineinchnick** [xo/usql#172]
Privilege related \d commands include:
* [x] \dp     [PATTERN]      list table, view, and sequence access privileges - with `\z` as an alias
* [ ] \ddp    [PATTERN]      list default privileges
* [ ] \dg[S+] [PATTERN]      list roles
* [ ] \du[S+] [PATTERN]      list roles
* [ ] \drds [PATRN1 [PATRN2]] list per-database role settings
