### ISSUE TITLE
Allow caching in completer

### ISSUE THREAD

**Issue by nineinchnick** [xo/usql#202]
Some databases, like Snowflake, are cloud-only and can have a considerable minimum query latency, noticeable when using auto-complete. Caching database identifiers, like tables and columns, would improve that.

Caching in the completer would be relatively easy to implement. There's already a method to filter reader's result sets locally.
* [ ] The cache should only be enabled by default for selected drivers (like Snowflake).
* [ ] There also has to be a way of disabling the cache entirely (a new setting).
* [ ] It should fetch data in a separate goroutine, that would allow using a higher than usual timeout (completer only has 3 sec timeout by default)
* [ ] The cache should be cleared on reconnect. Depends on #203

**Comment by nineinchnick** [comment]
`psql` allows to reconnect with `\c -reuse-previous=on` but we could add an alias for that.
